In [1]:
import numpy as np

a=np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [2]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()

print("time taken",(toc-tic)*1000) #for expressing in ms

time taken 2.0020008087158203


In [3]:
#without vectroziation
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print((toc-tic)*1000)

376.92737579345703


In [4]:
a=np.random.rand(5,4)
b=np.exp(a)
print (a)
print (b)



[[0.08718216 0.03351482 0.60167727 0.42373664]
 [0.33822159 0.14683087 0.30715719 0.27383785]
 [0.99501839 0.04545713 0.15062145 0.69872481]
 [0.54981592 0.41781404 0.13705067 0.05786065]
 [0.66722124 0.99880474 0.42198047 0.26362723]]
[[1.09109541 1.03408277 1.82517754 1.52765922]
 [1.40245124 1.15815807 1.35955466 1.31500155]
 [2.70477409 1.04650614 1.16255649 2.01118643]
 [1.73293399 1.51863824 1.14688626 1.05956734]
 [1.94881451 2.7150347  1.52497874 1.30164289]]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6]])
vertical_sum=a.sum(axis=0)
horizontal_sum=a.sum(axis=1)
horizontal_sum,vertical_sum



(array([10, 18]), array([ 4,  6,  8, 10]))

In [6]:
import numpy as np
a=np.random.rand(5)#dont do this
print(a.shape)#this is called as RANK 1 array  

(5,)


In [7]:
import numpy as np
a=np.random.rand(5,1)#do this to be more specific
print(a.shape)

(5, 1)


In [8]:
assert(a.shape==(5,2))# you can run this and make sure its a 5,1 and not some other dimension 


AssertionError: 

In [ ]:
#DONT HAVE RANK 1 ARRAYS  ,use only row and coloumn vectors

In [ ]:
import pip
pip install "jupyterlab-kite>=2.0.2"



In [ ]:
hello


In [ ]:
"hello"

In [10]:
a = a = np.random.randn(4, 3)
b = np.random.randn(3, 2) 
c=a*b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [12]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b 
c.shape
c

array([[ 1.45640861, -0.29303812, -1.26267629],
       [ 0.39602824, -0.44007508, -0.16043986],
       [-0.9022807 ,  0.2423274 , -0.3677166 ]])

In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c=a*b
c
c.shape


(3, 3)

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, -1)

print(newarr)

print("You are allowed to have one unknown dimension.Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.Pass -1 as the value, and NumPy will calculate this number for you.")

[[1 2 3 4]
 [5 6 7 8]]
You are allowed to have one unknown dimension.Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.Pass -1 as the value, and NumPy will calculate this number for you.
